name: 'PHPUnit for Symfony'
description: 'PHPUnit via Symfony bridge'
author: 'Fabrice Gyre (Proglab)'
branding:
    icon: 'check-circle'
    color: 'purple'
runs:
    using: 'docker'
    image: 'Dockerfile'
